### ISSUE TITLE
Package Alive?

### ISSUE THREAD

**Issue by slakbal** [teodortalov/citrix#15]
Hi there,

I really enjoy you package and has made life for me easier. It would really interest me to hear how it came about that you built it in the first place. Also are you going to maintain it further going forward?

Thanks!

**Comment by teodortalov** [comment]
Yes I maintain the package, and as any open source project help is always appreciated.

How it came about: I was working on a project and I needed to interface with GoToWebinar and there was nothing I liked so I created that package. Quite a few people have wrote me about it and even NetTuts mentioned me I one of their articles.

Does that answer your question! Do you need anything from me as far as the package goes? Any problems? Would you be interested in contributing?

Teodor

**Comment by teodortalov** [comment]
Merged! :+1:
