### ISSUE TITLE
Getting the error.. Please help

### ISSUE THREAD

**Issue by nisamp17** [teodortalov/citrix#18]
Fatal error: Call to a member function getRegistrationUrl() on boolean in

**Comment by teodortalov** [comment]
@nisamp17, thanks for reporting this issue.

I think this is a non-issue, I think you dont have any webinars to retrieve that's why you are getting the error.

You should make sure you are checking if there are webinars returned by GoToWebinar

Here is what you should do:

```
//get upcoming weibnars
$goToWebinar = new \Citrix\GoToWebinar($client);
$webinars = $goToWebinar->getUpcoming();


//here you should check if any webinars are returned like so:
if($webinars->count() > 0){

//get the first webinar
$webinar = reset($webinars);

//get registration URL, and this should work. 
$registrationUrl = $webinar->getRegistrationUrl();
}

```
