### ISSUE TITLE
 Undefined index: registrationUrl 

### ISSUE THREAD

**Issue by Jamongkad** [teodortalov/citrix#2]
Hello great library btw! I'm using it alongside the Laravel framework. Whenever I use this code I

$goToWebinar = new \Citrix\GoToWebinar($client); //@see $client definition above 
$webinars = $goToWebinar->getUpcoming();
var_dump($webinars) //this gives you all upcoming webinars

I get the "Undefined index: registrationUrl" error.  /citrix/src/Citrix/Entity/Webinar.php line 98.

What seems to be the problem?

**Comment by teodortalov** [comment]
This issue has been resolved.
